on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir kinss

      - uses: actions/checkout@v2
        with:
          path: kinss

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/kinss
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kinss:latest

      - name: Depoly to flyio, using fly.toml
        uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy ./kinss"